package com.example.synsoft.managewallet.model;

import java.util.List;
import com.example.synsoft.managewallet.model.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CATEGORY".
 */
public class Category {

    private Long id;
    private String name;
    private Long expenditureId;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient CategoryDao myDao;

    private ExpenditureType expenditureType;
    private Long expenditureType__resolvedKey;

    private List<IncomeExpense> incomeExpenses;

    public Category() {
    }

    public Category(Long id) {
        this.id = id;
    }

    public Category(Long id, String name, Long expenditureId) {
        this.id = id;
        this.name = name;
        this.expenditureId = expenditureId;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getCategoryDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getExpenditureId() {
        return expenditureId;
    }

    public void setExpenditureId(Long expenditureId) {
        this.expenditureId = expenditureId;
    }

    /** To-one relationship, resolved on first access. */
    public ExpenditureType getExpenditureType() {
        Long __key = this.expenditureId;
        if (expenditureType__resolvedKey == null || !expenditureType__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            ExpenditureTypeDao targetDao = daoSession.getExpenditureTypeDao();
            ExpenditureType expenditureTypeNew = targetDao.load(__key);
            synchronized (this) {
                expenditureType = expenditureTypeNew;
            	expenditureType__resolvedKey = __key;
            }
        }
        return expenditureType;
    }

    public void setExpenditureType(ExpenditureType expenditureType) {
        synchronized (this) {
            this.expenditureType = expenditureType;
            expenditureId = expenditureType == null ? null : expenditureType.getId();
            expenditureType__resolvedKey = expenditureId;
        }
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<IncomeExpense> getIncomeExpenses() {
        if (incomeExpenses == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            IncomeExpenseDao targetDao = daoSession.getIncomeExpenseDao();
            List<IncomeExpense> incomeExpensesNew = targetDao._queryCategory_IncomeExpenses(id);
            synchronized (this) {
                if(incomeExpenses == null) {
                    incomeExpenses = incomeExpensesNew;
                }
            }
        }
        return incomeExpenses;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetIncomeExpenses() {
        incomeExpenses = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    @Override
    public String toString() {
        return ""+getName();
    }
}
