package com.example.synsoft.managewallet.model;

import java.util.List;
import com.example.synsoft.managewallet.model.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CURRENCY".
 */
public class Currency {

    private Long id;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String notation;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient CurrencyDao myDao;

    private List<IncomeExpense> incomeExpenses;

    public Currency() {
    }

    public Currency(Long id) {
        this.id = id;
    }

    public Currency(Long id, String name, String notation) {
        this.id = id;
        this.name = name;
        this.notation = notation;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getCurrencyDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getNotation() {
        return notation;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNotation(String notation) {
        this.notation = notation;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<IncomeExpense> getIncomeExpenses() {
        if (incomeExpenses == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            IncomeExpenseDao targetDao = daoSession.getIncomeExpenseDao();
            List<IncomeExpense> incomeExpensesNew = targetDao._queryCurrency_IncomeExpenses(id);
            synchronized (this) {
                if(incomeExpenses == null) {
                    incomeExpenses = incomeExpensesNew;
                }
            }
        }
        return incomeExpenses;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetIncomeExpenses() {
        incomeExpenses = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    @Override
    public String toString() {
        return getName()+" "+getNotation();
    }
}
