package com.example.synsoft.managewallet.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.synsoft.managewallet.model.Currency;
import com.example.synsoft.managewallet.model.ExpenditureType;
import com.example.synsoft.managewallet.model.Category;
import com.example.synsoft.managewallet.model.IncomeExpense;

import com.example.synsoft.managewallet.model.CurrencyDao;
import com.example.synsoft.managewallet.model.ExpenditureTypeDao;
import com.example.synsoft.managewallet.model.CategoryDao;
import com.example.synsoft.managewallet.model.IncomeExpenseDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig currencyDaoConfig;
    private final DaoConfig expenditureTypeDaoConfig;
    private final DaoConfig categoryDaoConfig;
    private final DaoConfig incomeExpenseDaoConfig;

    private final CurrencyDao currencyDao;
    private final ExpenditureTypeDao expenditureTypeDao;
    private final CategoryDao categoryDao;
    private final IncomeExpenseDao incomeExpenseDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        currencyDaoConfig = daoConfigMap.get(CurrencyDao.class).clone();
        currencyDaoConfig.initIdentityScope(type);

        expenditureTypeDaoConfig = daoConfigMap.get(ExpenditureTypeDao.class).clone();
        expenditureTypeDaoConfig.initIdentityScope(type);

        categoryDaoConfig = daoConfigMap.get(CategoryDao.class).clone();
        categoryDaoConfig.initIdentityScope(type);

        incomeExpenseDaoConfig = daoConfigMap.get(IncomeExpenseDao.class).clone();
        incomeExpenseDaoConfig.initIdentityScope(type);

        currencyDao = new CurrencyDao(currencyDaoConfig, this);
        expenditureTypeDao = new ExpenditureTypeDao(expenditureTypeDaoConfig, this);
        categoryDao = new CategoryDao(categoryDaoConfig, this);
        incomeExpenseDao = new IncomeExpenseDao(incomeExpenseDaoConfig, this);

        registerDao(Currency.class, currencyDao);
        registerDao(ExpenditureType.class, expenditureTypeDao);
        registerDao(Category.class, categoryDao);
        registerDao(IncomeExpense.class, incomeExpenseDao);
    }
    
    public void clear() {
        currencyDaoConfig.getIdentityScope().clear();
        expenditureTypeDaoConfig.getIdentityScope().clear();
        categoryDaoConfig.getIdentityScope().clear();
        incomeExpenseDaoConfig.getIdentityScope().clear();
    }

    public CurrencyDao getCurrencyDao() {
        return currencyDao;
    }

    public ExpenditureTypeDao getExpenditureTypeDao() {
        return expenditureTypeDao;
    }

    public CategoryDao getCategoryDao() {
        return categoryDao;
    }

    public IncomeExpenseDao getIncomeExpenseDao() {
        return incomeExpenseDao;
    }

}
